# This file was generated by GoReleaser. DO NOT EDIT.
class Nancy < Formula
  desc "Tool to check for vulnerabilities in Go dependencies"
  homepage "https://nancy.dev"
  version "0.0.4"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/nrcook/nancy/releases/download/v0.0.4/nancy_Darwin_x86_64.tar.gz"
    sha256 "bfe90925065d5629a7431d69a428eaa7d9326411fba02e7b384ab8fe24e224e0"
  elsif OS.linux?
    url "https://github.com/nrcook/nancy/releases/download/v0.0.4/nancy_Linux_x86_64.tar.gz"
    sha256 "179afd072191965d911d93985faecc0b165930959cd0ea0268c409182d58eab7"
  end

  def install
    bin.install "nancy"
  end

  test do
    system "#{bin}/nancy -v"
  end
end
